//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SplatAIO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SplatAIO.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rank number is .
        /// </summary>
        public static string BAD_MAE_1 {
            get {
                return ResourceManager.GetString("BAD_MAE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . (The game displays invalid values as the max.) This may have been caused by a bad tool/script, such as the max stats script that used to be on the Modding Hub. Do you want to change it to 99, the maximum, to fix it? (You can change it to another value later.) If you select &quot;No&quot; here, the true value will not display in the AIO and you are at risk for a ban..
        /// </summary>
        public static string BAD_MAE_2 {
            get {
                return ResourceManager.GetString("BAD_MAE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your coins are set to .
        /// </summary>
        public static string BAD_OKANE_1 {
            get {
                return ResourceManager.GetString("BAD_OKANE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . (The game displays invalid values as the max.) This may have been caused by a bad tool/script, such as the max stats script that used to be on the Modding Hub. Do you want to change it to 9999999, the maximum, to fix it? (You can change it to another value later.) If you select &quot;No&quot; here, the true value will not display in the AIO and you are at risk for a ban..
        /// </summary>
        public static string BAD_OKANE_2 {
            get {
                return ResourceManager.GetString("BAD_OKANE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your level is .
        /// </summary>
        public static string BAD_RANK_1 {
            get {
                return ResourceManager.GetString("BAD_RANK_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . (The game displays invalid values as the max.) This may have been caused by a bad tool/script, such as the max stats script that used to be on the Modding Hub. Do you want to change it to 50, the maximum, to fix it? (You can change it to another value later.) If you select &quot;No&quot; here, the true value will not display in the AIO and you are at risk for a ban..
        /// </summary>
        public static string BAD_RANK_2 {
            get {
                return ResourceManager.GetString("BAD_RANK_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your super sea snails are set to .
        /// </summary>
        public static string BAD_SAZAE_1 {
            get {
                return ResourceManager.GetString("BAD_SAZAE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . (The game displays invalid values as the max.) This may have been caused by a bad tool/script, such as the max stats script that used to be on the Modding Hub. Do you want to change it to 999, the maximum, to fix it? (You can change it to another value later.) If you select &quot;No&quot; here, the true value will not display in the AIO and you are at risk for a ban..
        /// </summary>
        public static string BAD_SAZAE_2 {
            get {
                return ResourceManager.GetString("BAD_SAZAE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rank is set to .
        /// </summary>
        public static string BAD_UDE_1 {
            get {
                return ResourceManager.GetString("BAD_UDE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . (The game displays invalid values as the max.) This may have been caused by a bad tool/script, such as the max stats script that used to be on the Modding Hub. Do you want to change it to 10 (S+), the maximum, to fix it? (You can change it to another value later.) If you select &quot;No&quot; here, the true value will not display in the AIO and you are at risk for a ban..
        /// </summary>
        public static string BAD_UDE_2 {
            get {
                return ResourceManager.GetString("BAD_UDE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all fields..
        /// </summary>
        public static string FILL_IN_ALL_FIELDS_TEXT {
            get {
                return ResourceManager.GetString("FILL_IN_ALL_FIELDS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string INVALID {
            get {
                return ResourceManager.GetString("INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid clear state..
        /// </summary>
        public static string INVALID_CLEAR_STATE {
            get {
                return ResourceManager.GetString("INVALID_CLEAR_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid level number..
        /// </summary>
        public static string INVALID_LEVEL_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_LEVEL_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This level has already been added. If you wish to edit it, please right click it in the list..
        /// </summary>
        public static string LEVEL_ALREADY_ADDED_TEXT {
            get {
                return ResourceManager.GetString("LEVEL_ALREADY_ADDED_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splat-AIO will reset all Octo Valley flags, removing all single player progress currently on your save file. Are you sure you want to continue?.
        /// </summary>
        public static string SINGLE_PLAYER_RESET_TEXT {
            get {
                return ResourceManager.GetString("SINGLE_PLAYER_RESET_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string SINGLE_PLAYER_RESET_TITLE {
            get {
                return ResourceManager.GetString("SINGLE_PLAYER_RESET_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
